### ISSUE TITLE
Support laravel 6.0

### ISSUE THREAD

**Issue by williamdes** [pixelpeter/laravel5-isocodes-validation#14]
https://github.com/pixelpeter/laravel5-isocodes-validation/blob/47527ef512196aaaddcd3345d315cda78b2e4d92/src/IsoCodesValidationServiceProvider.php#L44

`snake_case` has been removed in laravel 5.9
I can confirm that this lib does not work with laravel 6.0
https://github.com/laravel/framework/pull/26898/files#diff-887b2fccb767c2cdab0e4d6964d55b13R830

**Comment by williamdes** [comment]
Laravel supports since ever the https://laravel.com/api/4.2/Illuminate/Support/Str.html#method_snake

**Comment by williamdes** [comment]
Adding [`laravel/helpers`](https://packagist.org/packages/laravel/helpers)

**Comment by pixelpeter** [comment]
I will take care of this this weekend. Thanks so far

**Comment by williamdes** [comment]
@pixelpeter did you have time to merge my PR ?

**Comment by blissgrn** [comment]
Any news ? I'll be interested about this merge too.

**Comment by KonradDeskiewicz** [comment]
Hi. It's a handful of weekends since this issue was brought up + there is even a PR waiting to be merged :) I'm waiting as well. L6 is already here, and adding helpers only to serve "isocodes" it's a bit stretched. Help us, please :)

**Comment by williamdes** [comment]
@pixelpeter Could you please close this issue with my PR ?

**Comment by williamdes** [comment]
No official message, closing.

**Comment by williamdes** [comment]
:ping_pong: :trollface:

**Comment by stebogit** [comment]
Hi, it looks like `v3.0.0` still does not include [the change to fix this issue](https://github.com/pixelpeter/laravel5-isocodes-validation/blob/master/src/IsoCodesValidationServiceProvider.php#L44); in fact the package still breaks on Laravel 6.

Likely you did not released the latest version. Would you mind publishing a new version, say `3.0.1`?

**Comment by williamdes** [comment]
We are waiting for @pixelpeter :)

**Comment by pixelpeter** [comment]
I've just created a new package https://github.com/pixelpeter/laravel-isocodes-validation which will support Laravel 8+
