### ISSUE TITLE
Planned support for ZIP+4?

### ISSUE THREAD

**Issue by iadambrown** [pixelpeter/laravel5-isocodes-validation#16]
Hi there, I was wondering if you're planning to support ZIP+4 in the package?

Currently, I have to omit the `zipcode:country` rule, as a ZIP+4 results in an error like "The value "12345-1234" of zipcode is not valid for "USA"."

Just here as a reference:
https://en.wikipedia.org/wiki/ZIP_Code#ZIP+4

Thanks!

**Comment by pixelpeter** [comment]
This package is only a wrapper for the https://github.com/ronanguilloux/IsoCodes library.
If it's supported there, I can implement it in this package
