### ISSUE TITLE
Auto-Discovery not working

### ISSUE THREAD

**Issue by ReckeDJ** [pixelpeter/laravel5-isocodes-validation#3]
Just installed v2.0.0, but Auto-Discovery is not working. I think you need something like this in your composer.json:

```
"extra": {
    "laravel": {
        "providers": [
            "Pixelpeter\\IsoCodesValidation\\IsoCodesValidationServiceProvider"
        ]
    }
}
```

**Comment by pixelpeter** [comment]
You're completely right.
Thanks for pointing this out !!
