### ISSUE TITLE
Support asterisks/wildacrds for validation rules with 'country'/Arr::get()

### ISSUE THREAD

**Issue by otr-tomek** [pixelpeter/laravel5-isocodes-validation#7]
Validation rule example:
`'shipments.*.from.zip' => 'zipcode:shipments.*.from.country_id'`

Sources:
- https://github.com/laravel/framework/issues/16183
- https://github.com/laravel/framework/blob/5a11fb13d7023e05911559c99902e68f3cb95ed9/src/Illuminate/Validation/Validator.php#L489

Can You add getExplicitKeys() and replaceAsterisksInParameters() like this?
 ```
       public function validateZipcode($attribute, $value, $parameters)
    {
        $this->requireParameterCount(1, $parameters, 'zipcode');

        // replace asterisk/wildcard '*' with $attribute index, example: 'shipments.*.from.country_id' -> shipments.0.from.country_id' ($this->currentRule)
        if ($keys = $this->getExplicitKeys($attribute)) {
            $parameters = $this->replaceAsterisksInParameters($parameters, $keys);
        }
        
        $country = Arr::get($this->data, $parameters[0], $parameters[0]);

        return $this->runIsoCodesValidator(\IsoCodes\ZipCode::class, $value, $country);
    }
```

**Comment by pixelpeter** [comment]
Unfortunately it's not that trivial.
Looks like I have to do some major refactoring.

**Comment by otr-tomek** [comment]
> Unfortunately it's not that trivial.
> Looks like I have to do some major refactoring.

It's working example -  in my project works great ;)

**Comment by pixelpeter** [comment]
What about error messages. 
Are these showing the correct data?
Is your source code somewhere available?

**Comment by pixelpeter** [comment]
Found a solution for the error messages.
Will have a look if I can implement it for every validator...

**Comment by pixelpeter** [comment]
Added support for arrays with dot notation to all validation methods in release v3.0.0
https://github.com/pixelpeter/laravel5-isocodes-validation/releases/tag/v3.0.0
